---
- name: "MEDIUM | CISC-L2-000010 | PATCH | The Cisco switch must be configured to disable non-essential capabilities."
  ios_config:
      lines: no {{ item }}
  with_items:
      - "{{ iosstig_non_essential_serv }}"
  when:
      - cisc_l2_000010
  tags:
      - CISC-L2-000010
      - CAT2
      - CCI-000381
      - SRG-NET-000131-L2S-000014
      - SV-220622r539671_rule
      - V-220622
      
- name: "MEDIUM | CISC-L2-000030 | PATCH | The Cisco switch must authenticate all VLAN Trunk Protocol (VTP) messages with a hash function using the most secured cryptographic algorithm available."
  block:
      - name: "MEDIUM | CISC-L2-000030 | AUDIT | The Cisco switch must authenticate all VLAN Trunk Protocol (VTP) messages with a hash function using the most secured cryptographic algorithm available. | Get VTP Mode"
        ios_command:
            commands: 
              - Show vtp status | include VTP Operating Mode
        register: cisc_l2_000030_vtp_mode

      - name: "MEDIUM | CISC-L2-000030 | AUDIT | The Cisco switch must authenticate all VLAN Trunk Protocol (VTP) messages with a hash function using the most secured cryptographic algorithm available. | Check operating mode is not off"
        ios_command:
            commands: 
                - show vtp password
        register: cisc_l2_000030_vtppassword
        when: '"VTP Operating Mode                : Off" not in cisc_l2_000030_vtp_mode.stdout'

      - name: MEDIUM | CISC-L2-000030 | PATCH | The Cisco switch must authenticate all VLAN Trunk Protocol (VTP) messages with a hash function using the most secured cryptographic algorithm available. | Set password"
        ios_command:  
            commands:
                - vtp password {{ iosstig_vtp_user_password }} 
        changed_when: true
        when: "'The VTP password is not configured.' in cisc_l2_000030_vtppassword.stdout"
  when:
      - cisc_l2_000030
  tags:
      - CISC-L2-000030
      - CAT2s
      - CCI-000803
      - SRG-NET-000168-L2S-000019
      - SV-220624r539671_rule
      - V-220624

- name: "MEDIUM | CISC-L2-000040 | PATCH | The Cisco switch must manage excess bandwidth to limit the effects of packet-flooding types of denial-of-service (DoS) attacks."
  ios_config:
      lines: 
          - mls qos
  when:
      - cisc_l2_000040
  tags:
      - CISC-L2-000040
      - CAT2
      - CCCI-001095
      - SRG-NET-000193-L2S-000020
      - SV-220625r539671_rule
      - V-220625

- name: "MEDIUM | CISC-L2-000060 | AUDIT | The Cisco switch must be configured for authorized users to select a user session to capture."
  block:
      - name: "MEDIUM | CISC-L2-000060 | PATCH | The Cisco switch must be configured for authorized users to select a user session to capture. | Set Source Interfaces"
        ios_config:
            lines: 
              - monitor session {{ item }}
        with_items:
            - "{{ iosstig_capture_session_source }}"
        when: "'none' not in iosstig_capture_session_source"

      - name: "MEDIUM | CISC-L2-000060 | PATCH | The Cisco switch must be configured for authorized users to select a user session to capture. | Set Destination Interfaces"
        ios_config:
            lines:
              - monitor session {{ item }}
        with_items:
            - "{{ iosstig_capture_session_destination }}"
        when: "'none' not in iosstig_capture_session_destination"
  when:
      - cisc_l2_000060
  tags:
      - CISC-L2-000060
      - CAT2
      - CCI-001919
      - SRG-NET-000331-L2S-000001
      - SV-220626r539671_rule
      - V-220626

- name: "MEDIUM | CISC-L2-000070 | AUDIT | The Cisco switch must be configured for authorized users to remotely view, in real time, all content related to an established user session from a component separate from the Cisco switch."
  block:
      - name: "MEDIUM | CISC-L2-000070 | PATCH | The Cisco switch must be configured for authorized users to remotely view, in real time, all content related to an established user session from a component separate from the Cisco switch. | Set Source Interfaces"
        ios_config:
            lines: 
              - monitor session {{ item }}
        with_items:
            - "{{ iosstig_remoteview_session_source }}"
        when: "'none' not in iosstig_remoteview_session_source"

      - name: "MEDIUM | CISC-L2-000070 | PATCH | The Cisco switch must be configured for authorized users to remotely view, in real time, all content related to an established user session from a component separate from the Cisco switch. | Set Destination Interfaces"
        ios_config:
            lines:
              - monitor session {{ item }}
        with_items:
            - "{{ iosstig_remoteview_session_destination }}"
        when: "'none' not in iosstig_remoteview_session_destination"
  when:
      - cisc_l2_000070
  tags:
      - CISC-L2-000070
      - CAT2
      - CCI-001920
      - SRG-NET-000332-L2S-000002
      - SV-220627r539671_rule
      - V-220627

- name: "MEDIUM | CISC-L2-000080 | PATCH | The Cisco switch must authenticate all endpoint devices before establishing any connection."
  ios_config:
      lines:
        - radius server {{ iosstig_radius_server_one_name }}
        - address ipv4 {{ iosstig_radius_server_one_ip }}
        - key {{ iosstig_radius_server_one_key }}
        - radius server {{ iosstig_radius_server_two_name }}
        - address ipv4 {{ iosstig_radius_server_two_ip }}
        - key {{ iosstig_radius_server_two_key }}
        - aaa new-model
        - aaa group server radius {{ iosstig_radius_group_name }}
        - server name {{ iosstig_radius_server_one_name }}
        - server name {{ iosstig_radius_server_two_name }}
        - aaa authentication dot1x default group {{ iosstig_radius_group_name }}
        - dot1x system-auth-control
        - interface range {{ iosstig_userfacing_ports }}
        - switchport mode access
        - authentication host-mode {{ iosstig_auth_hostmode }}
        - dot1x pae authenticator
        - authentication port-control auto
  when:
      - cisc_l2_000080
  tags:
      - CISC-L2-000080
      - CAT2
      - CCI-001958
      - SRG-NET-000343-L2S-000016
      - SV-220628r539671_rule
      - V-220628

- name: "MEDIUM | CISC-L2-000100 | AUDIT |  The Cisco switch must have Bridge Protocol Data Unit (BPDU) Guard enabled on all user-facing or untrusted access switch ports."
  block:
      - name: "MEDIUM | CISC-L2-000100 | PATCH |  The Cisco switch must have Bridge Protocol Data Unit (BPDU) Guard enabled on all user-facing or untrusted access switch ports. | Global BPDU Guard."
        ios_config:
            lines: 
              - spanning-tree portfast bpduguard default
        when: "'none' not in iosstig_bpdu_guard_global"

      - name: "MEDIUM | CISC-L2-000100 | PATCH |  The Cisco switch must have Bridge Protocol Data Unit (BPDU) Guard enabled on all user-facing or untrusted access switch ports. | Per Interface BPDU Guard."
        ios_config:
            lines:
              - interface range {{ iosstig_bpdu_guard_interfaces }} 
              - spanning-tree bpduguard enable
        when: "'none' not in iosstig_bpdu_guard_interfaces"
  when:
      - cisc_l2_000100
  tags:
      - CISC-L2-000100
      - CAT2
      - CCI-002385
      - SRG-NET-000362-L2S-000022
      - SV-220630r539671_rule
      - V-220630

- name: "MEDIUM | CISC-L2-000110 | PATCH | The Cisco switch must have Spanning Tree Protocol (STP) Loop Guard enabled."
  ios_config:
      lines: 
        - spanning-tree loopguard default
  when:
      - cisc_l2_000110
  tags:
      - CISC-L2-000110
      - CAT2
      - CCI-002385
      - SRG-NET-000362-L2S-000023
      - SV-220631r539671_rule
      - V-220631
  
- name: "MEDIUM | CISC-L2-000120 | PATCH | The Cisco switch must have Unknown Unicast Flood Blocking (UUFB) enabled."
  ios_config:
      lines:
        - interface range {{ item }} 
        - switchport block unicast
  loop:
        - "{{ iosstig_userfacing_ports }}"
        - "{{ iosstig_untrusted_ports }}"
        - "{{ iosstig_blackhole_ports }}"
  when:
      - cisc_l2_000120
  tags:
      - CISC-L2-000120
      - CAT2
      - CCI-002385
      - SRG-NET-000362-L2S-000024
      - SV-220632r539671_rule
      - V-220632

- name: "MEDIUM | CISC-L2-000130 | PATCH | The Cisco switch must have DHCP snooping for all user VLANs to validate DHCP messages from untrusted sources."
  ios_config:
        lines: 
          - ip dhcp snooping vlan {{ iosstig_user_vlans }}
  when:
      - cisc_l2_000130
  tags:
      - CISC-L2-000130
      - CAT2
      - CCI-002385
      - SRG-NET-000362-L2S-000025
      - V-220633r539671_rule
      - V-220633

- name: "MEDIUM | CISC-L2-000140 | PATCH | The Cisco switch must have IP Source Guard enabled on all user-facing or untrusted access switch ports."
  ios_config:
      lines:
          - interface range {{ iosstig_sourceguard_option }}
          - ip verify source
  when:
      - cisc_l2_000140
  tags:
      - CISC-L2-000140
      - CAT2
      - CCI-002385
      - SRG-NET-000362-L2S-000026
      - SV-220634r744220_rule
      - V-220634

- name: "MEDIUM | CISC-L2-000150 | PATCH | The Cisco switch must have Dynamic Address Resolution Protocol (ARP) Inspection (DAI) enabled on all user VLANs."
  ios_config:
        lines: 
          - ip arp inspection vlan {{ iosstig_user_vlans }}
  when:
      - cisc_l2_000150
  tags:
      - CISC-L2-000150
      - CAT2
      - CCI-002385
      - SRG-NET-000362-L2S-000027
      - SV-220635r539671_rule
      - V-220635

- name: "MEDIUM | CISC-L2-000180 | AUDIT | The Cisco switch must implement Rapid Spanning Tree Protocol (STP) where VLANs span multiple switches with redundant links."
  block:
      - name: "MEDIUM | CISC-L2-000180 | PATCH | The Cisco switch must implement Rapid Spanning Tree Protocol (STP) where VLANs span multiple switches with redundant links. | Set Spanning Tree Mode."
        ios_config:
            lines: 
              - spanning-tree mode {{ iosstig_spanningtree_mode }}

      - name: "MEDIUM | CISC-L2-000180 | AUDIT | The Cisco switch must implement Rapid Spanning Tree Protocol (STP) where VLANs span multiple switches with redundant links. | Wait For Change."
        wait_for_connection:
          delay: 35
          timeout: 40

      - name: "MEDIUM | CISC-L2-000180 | PATCH | The Cisco switch must implement Rapid Spanning Tree Protocol (STP) where VLANs span multiple switches with redundant links. Prune VLAN's From Spanning-Tree."
        ios_config:
            lines: 
              - no spanning-tree vlan {{ iosstig_spanningtree_remove_vlans }}
        when: "'none' not in iosstig_spanningtree_remove_vlans"

      - name: "MEDIUM | CISC-L2-000180 | PATCH | The Cisco switch must implement Rapid Spanning Tree Protocol (STP) where VLANs span multiple switches with redundant links. | Add VLAN's Back Into Spanning-Tree."
        ios_config:
            lines: 
              - spanning-tree vlan {{ iosstig_spanningtree_add_vlans }}
        when: "'none' not in iosstig_spanningtree_add_vlans"  
  when:
      - cisc_l2_000180
  tags:
      - CISC-L2-000180
      - CAT2
      - CCI-000366
      - SRG-NET-000512-L2S-000003
      - SV-220638r539671_rule
      - V-220638

- name: "MEDIUM | CISC-L2-000190 | AUDIT | The Cisco switch must enable Unidirectional Link Detection (UDLD) to protect against one-way connections."
  block:
      - name: "MEDIUM | CISC-L2-000190 | PATCH | The Cisco switch must enable Unidirectional Link Detection (UDLD) to protect against one-way connections. | Global UDLD Enable"
        ios_config:
            lines: 
              - udld enable
        when: "'none' not in iosstig_udld_global"

      - name: "MEDIUM | CISC-L2-000190 | PATCH | The Cisco switch must enable Unidirectional Link Detection (UDLD) to protect against one-way connections. | Interface UDLD Enable"
        ios_config:
            lines:
              - interface range {{ iosstig_udld_interface }} 
              - udld port
        when: "'none' not in iosstig_udld_interface"
  when:
      - cisc_l2_000190
  tags:
      - CISC-L2-000190
      - CAT2
      - CCI-000366
      - SRG-NET-000512-L2S-000004
      - SV-220639r539671_rule
      - V-220639

- name: "MEDIUM | CISC-L2-000200 | PATCH | The Cisco switch must have all trunk links enabled statically."
  ios_config:
      lines:
        - interface range {{ iosstig_trunk_ports }}
        - switchport trunk encapsulation dot1q
        - switchport mode trunk
        - switchport nonegotiate 
  when:
      - cisc_l2_000200
  tags:
      - CISC-L2-000200
      - CAT2
      - CCI-000366
      - SRG-NET-000512-L2S-000005
      - SV-220640r539671_rule
      - V-220640

- name: "MEDIUM | CISC-L2-000210 | AUDIT | The Cisco switch must have all disabled switch ports assigned to an unused VLAN."
  block:
      - name: "MEDIUM | CISC-L2-000210 | PATCH | The Cisco switch must have all disabled switch ports assigned to an unused VLAN. | Create Blackhole VLAN And Name It."
        ios_vlans:
            config: 
                - vlan_id: "{{ iosstig_blackhole_vlan }}"
                  name: "{{ iosstig_blackhole_vlan_name }}"
                  shutdown: disabled
            state: merged  

      - name: "MEDIUM | CISC-L2-000210 | PATCH | The Cisco switch must have all disabled switch ports assigned to an unused VLAN. | Assign Inactive Ports To VLAN and Shutdown."
        ios_config:
            lines: 
                - interface range {{ iosstig_blackhole_ports }}
                - switchport access vlan {{ iosstig_blackhole_vlan }}
                - shutdown

      - name: "MEDIUM | CISC-L2-000210 | PATCH | The Cisco switch must have all disabled switch ports assigned to an unused VLAN. | Remove Blackhole VLAN From Trunk Ports."
        ios_config:
            lines: 
              - interface range {{ iosstig_trunk_ports }}
              - switchport trunk allowed vlan except {{ iosstig_blackhole_vlan }} 
  when:
      - cisc_l2_000210
  tags:
      - CISC-L2-000210
      - CAT2
      - CCI-000366
      - SRG-NET-000512-L2S-000007
      - SV-220641r539671_rule
      - V-220641

- name: "MEDIUM | CISC-L2-000220 | AUDIT | The Cisco switch must not have the default VLAN assigned to any host-facing switch ports."
  block:
      - name: "MEDIUM | CISC-L2-000220 | AUDIT | The Cisco switch must not have the default VLAN assigned to any host-facing switch ports. | Get VLAN Status."
        ios_command:
          commands:
            - show vlan
        register: cisc_l2_000270_vlaninfo
        
      - name: "MEDIUM | CISC-L2-000220 | AUDIT | The Cisco switch must not have the default VLAN assigned to any host-facing switch ports. | Message Out"
        debug:
          msg:
              - "Warning! Below are the ports that are on the default VLAN"
              - "To conform to STIG standards make sure these access switch ports are assigned to the correct VLANS."
              - "{{ cisc_l2_000270_vlaninfo.stdout_lines }}"
  when:
      - cisc_l2_000220
  tags:
      - CISC-L2-000220
      - CAT2
      - CCI-000366
      - SRG-NET-000512-L2S-000008
      - SV-220642r539671_rule
      - V-220642

- name: "MEDIUM | CISC-L2-000230 | PATCH | The Cisco switch must have the default VLAN pruned from all trunk ports that do not require it."
  ios_config:
            lines:
              - interface range {{ iosstig_trunk_ports }}
              - switchport trunk allowed vlan except 1,{{ iosstig_blackhole_vlan }}
  when:
      - cisc_l2_000230
  tags:
      - CISC-L2-000230
      - CAT2
      - CCI-000366
      - SRG-NET-000512-L2S-000009
      - SV-220643r539671_rule
      - V-220643

- name: "MEDIUM | CISC-L2-000240 | AUDIT | The Cisco switch must not use the default VLAN for management traffic."
  block:
      - name: "MEDIUM | CISC-L2-000240 | PATCH | The Cisco switch must not use the default VLAN for management traffic. | Set New Management VLAN."
        ios_config:
            lines: 
              - interface vlan {{ iosstig_mgmt_vlan }}
              - description {{ iosstig_mgmt_vlan_name }}
              - ip address {{ iosstig_mgmt_ipaddress }} {{ iosstig_mgmt_ipaddress_subnet }}
              - no shutdown
  when:
      - cisc_l2_000240
  tags:
      - CISC-L2-000240
      - CAT2
      - CCI-000366
      - SRG-NET-000512-L2S-000010
      - SV-220644r539671_rule
      - V-220644

- name: "MEDIUM | CISC-L2-000250 | AUDIT | The Cisco switch must have all user-facing or untrusted ports configured as access switch ports."
  block:
      - name: "MEDIUM | CISC-L2-000250 | PATCH | The Cisco switch must have all user-facing or untrusted ports configured as access switch ports. | Set Userfacing."
        ios_config:
            lines:
              - interface range {{ iosstig_setaccess_switchports }}
              - switchport mode access
  when:
      - cisc_l2_000250
  tags:
      - CISC-L2-000250
      - CAT2
      - CCI-000366
      - SRG-NET-000512-L2S-000011
      - SV-220645r539671_rule
      - V-220645

- name: "MEDIUM | CISC-L2-000260 | AUDIT | The Cisco switch must have the native VLAN assigned to an ID other than the default VLAN for all 802.1q trunk links."
  block:
      - name: "MEDIUM | CISC-L2-000260 | PATCH | The Cisco switch must have the native VLAN assigned to an ID other than the default VLAN for all 802.1q trunk links. | Setup New Native Vlan & Name."
        ios_config:
            lines: 
                - vlan {{ iosstig_native_vlan }}
                - name {{ iosstig_native_vlan_name }}
      - name: "MEDIUM | CISC-L2-000260 | PATCH | The Cisco switch must have the native VLAN assigned to an ID other than the default VLAN for all 802.1q trunk links. | Apply New Native VLAN To Trunk Ports."
        ios_config:
            lines: 
                - interface range {{ iosstig_trunklink_interfaces_native }}
                - switchport trunk native vlan {{ iosstig_native_vlan }}
  when:
      - cisc_l2_000260
  tags:
      - CISC-L2-000260
      - CAT2
      - CCI-000366
      - SRG-NET-000512-L2S-000012
      - SV-220646r539671_rule
      - V-220646